# Generated by Django 3.2.9 on 2021-11-17 08:14

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0002_auto_20211023_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantype',
            name='name',
            field=models.CharField(choices=[('FORECAST', 'Forecast'), ('BUDGET', 'Budget')], default='FORECAST', max_length=50, verbose_name='Plan Type'),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='year',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=sales.models.PlanType.current_year),
        ),
        migrations.AlterField(
            model_name='salesplan',
            name='cpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customerplantype', verbose_name='Customer Plan'),
        ),
        migrations.CreateModel(
            name='CustomerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='portfolio',
            
        ),
        migrations.AddField(
            model_name='customer',
            name='portfolio',
            field=models.ManyToManyField(blank=True, through='sales.CustomerPortfolio', to='products.Product'),
        ),
    ]
