# Generated by Django 3.2.9 on 2021-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customerportfolio_sales_customerportfolio_is_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesplan',
            name='sales_salesplan_is_unique',
        ),
        migrations.RenameField(
            model_name='salesplan',
            old_name='period',
            new_name='period_start',
        ),
        migrations.AddField(
            model_name='salesplan',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='salesplan',
            constraint=models.UniqueConstraint(fields=('period_start', 'cpt'), name='sales_salesplan_is_unique'),
        ),
    ]
